# Generated by Django 3.0 on 2019-12-19 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_dberdetail_linked'),
    ]

    operations = [
        migrations.CreateModel(
            name='AadharNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='dberdetail',
            name='aadhar_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.AadharNo'),
        ),
    ]
