# Generated by Django 3.0 on 2019-12-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191219_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadharno',
            name='number',
            field=models.CharField(max_length=12),
        ),
    ]
