# Generated by Django 3.0 on 2019-12-20 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_dberdetail_email_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='dberdetail',
            name='user_detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
