# Generated by Django 3.0 on 2019-12-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_dberdetail_user_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dberdetail',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='dberdetail',
            name='last_name',
        ),
        migrations.AddField(
            model_name='dberdetail',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
