# Generated by Django 2.2.7 on 2019-12-18 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191218_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dberdetail',
            name='DOB',
            field=models.DateField(),
        ),
    ]
