# Generated by Django 3.0 on 2019-12-19 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191219_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='dberdetail',
            name='linked',
            field=models.BooleanField(default=False),
        ),
    ]
