# Generated by Django 3.0 on 2019-12-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191219_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='dberdetail',
            name='email_address',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
