# Generated by Django 3.0 on 2019-12-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20191220_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dberdetail',
            name='aadhar_no',
            field=models.CharField(max_length=12),
        ),
        migrations.DeleteModel(
            name='AadharNo',
        ),
    ]
