# Generated by Django 3.0 on 2019-12-20 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_staffdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffdetail',
            name='email_address',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
